### ISSUE TITLE
headline-jump plugin breaks sidebar drag n drop of images to textarea

### ISSUE THREAD

**Issue by bnomei** [jenstornell/kirby-headline-jump#5] opened 2017-06-23 07:28 UTC
https://forum.getkirby.com/t/panel-sidebar-image-drop-to-textarea-field-creating-kirbytag-broken/7789

**Comment by bnomei** [comment] 2017-06-23 07:37
using kirby 2.4.1

**Comment by bnomei** [comment] 2017-07-03 08:44
any progress in tracking down this bug?

**Comment by jenstornell** [comment] 2017-07-03 09:19
It's not on my todo list right now, but because you made a donation partly to this plugin I will look into this today. I can't promise that I can fix it, because I don't know the cause yet but I will look into it and tell you how it went, probably later today.

**Comment by bnomei** [comment] 2017-07-03 09:21
thanks that would be great. otherwise i would have to remove the plugin from my clients panel installation asap.

**Comment by jenstornell** [comment] 2017-07-03 12:04
I just uploaded a fix. In fact it's a rewrite of the js code. Because Kirby probably will never drop jQuery I have change from vanilla js to jQuery. It works for me, hopefully for you as well. I close it.

**Closed as completed by jenstornell** 2017-07-03 12:04 UTC
